change to bash

diff --git a/bin/quickdraw b/bin/quickdraw
--- a/bin/quickdraw
+++ b/bin/quickdraw
@@ -1,4 +1,5 @@
-#!/bin/sh -e
+#!/bin/bash
+set -e # Stop on errors
 
 sh bin/setup
 
diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,12 +1,13 @@
-#!/bin/sh -e
+#!/bin/bash
+set -e # Stop on errors
 
-if ! [ -f ".env" ]; then
+if [ ! -f ".env" ]; then
   cp .env.default .env
 fi
 
 export $(cat .env | sed 's/#.*//g'| xargs)
 
-if ! [ -d "container" ]; then
+if [ ! -d "container" ]; then
   mkdir container
 fi
 
